# Generated by Django 4.0.6 on 2022-07-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_item_item_data_item_item_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_data',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_media',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
